---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata: 
      labels:
        app: helloworld
        app.kubernetes.io/part-of: DEMOAPP
        app.kubernetes.io/version: "1.23"
    spec:
      containers:
      - name: helloworld
        image: nginxdemos/hello:0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: DT_APPLICATION_ENVIRONMENT
          value: "STUDENTXXX"
        - name: DT_TAGS
          value: "HELLOWORLD_STUDENTXXX"
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15