---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata: 
      labels:
        app: helloworld
        app.kubernetes.io/name: HELLOWORLD
        app.kubernetes.io/instance: INSTANCE
        app.kubernetes.io/component: COMPONENT
        app.kubernetes.io/part-of: APPLICATION
        app.kubernetes.io/managed-by: MANUAL
        app.kubernetes.io/version: 1.23        
    spec:
      containers:
      - name: helloworld
        image: hello-world:linux
        imagePullPolicy: IfNotPresent
        env:
        - name: DT_APPLICATION_ENVIRONMENT
          value: "STUDENTXXX"
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi